#!/usr/bin/env -S node --experimental-strip-types
/**
 * Internal-linking audit — walks every built HTML page in `dist/`,
 * extracts internal `<a href="…">` targets, and reports:
 *
 * - Orphan pages: pages reachable from the sitemap but not linked from
 *   any other page (low link equity, harder for crawlers to find).
 * - Hub pages: pages with the most inbound internal links.
 * - Broken internal links: hrefs pointing to URLs that don't exist in dist.
 *
 * Usage:
 *   pnpm run links:audit
 *
 * Reads dist/sitemap-*.xml to enumerate the site's authoritative URL set.
 * Pure Node 20+, no external dependencies.
 */

import fs from 'node:fs';
import path from 'node:path';

const DIST = path.join(process.cwd(), 'dist');

function* walkHtml(dir: string): Generator<string> {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const f = path.join(dir, e.name);
    if (e.isDirectory()) yield* walkHtml(f);
    else if (e.isFile() && e.name.endsWith('.html')) yield f;
  }
}

/** Convert a dist HTML file path to its public URL path with trailing slash. */
function fileToPath(file: string): string {
  let rel = path.relative(DIST, file).replace(/\\/g, '/');
  rel = rel.replace(/index\.html$/, '');
  rel = rel.replace(/\.html$/, '/');
  if (!rel.startsWith('/')) rel = '/' + rel;
  if (rel === '/') return '/';
  return rel;
}

/** Normalize an href to a comparable site-relative path. Returns null if
 *  the link is external, an anchor, mailto, etc. */
function normalize(href: string, fromPath: string): string | null {
  if (!href) return null;
  if (href.startsWith('#') || href.startsWith('mailto:') || href.startsWith('tel:')) return null;
  if (/^[a-z]+:\/\//i.test(href)) {
    // Allow same-origin absolute URLs.
    try {
      const u = new URL(href);
      if (u.host !== 'grow.glitchexecutor.com') return null;
      let p = u.pathname;
      if (!p.endsWith('/') && !/\.[a-z0-9]+$/i.test(p)) p += '/';
      return p;
    } catch { return null; }
  }
  // Relative: resolve against fromPath.
  let resolved: string;
  if (href.startsWith('/')) {
    resolved = href;
  } else {
    const base = fromPath.endsWith('/') ? fromPath : fromPath.replace(/[^/]+$/, '');
    resolved = new URL(href, 'https://x' + base).pathname;
  }
  // Drop query + hash.
  resolved = resolved.split(/[?#]/)[0];
  // Add trailing slash unless it has a file extension.
  if (!resolved.endsWith('/') && !/\.[a-z0-9]+$/i.test(resolved)) resolved += '/';
  return resolved;
}

const HREF_RE = /\bhref=["']([^"']+)["']/gi;

interface AuditData {
  pages: Set<string>;
  inbound: Map<string, Set<string>>;  // page → set of pages linking to it
  outbound: Map<string, Set<string>>; // page → set of pages it links to
  broken: Array<{ from: string; to: string }>;
}

function audit(): AuditData {
  const pages = new Set<string>();
  const inbound = new Map<string, Set<string>>();
  const outbound = new Map<string, Set<string>>();
  const broken: Array<{ from: string; to: string }> = [];

  // First pass — enumerate all pages.
  const files: string[] = [];
  for (const f of walkHtml(DIST)) {
    files.push(f);
    pages.add(fileToPath(f));
  }

  // Second pass — collect outbound links.
  for (const f of files) {
    const fromPath = fileToPath(f);
    const html = fs.readFileSync(f, 'utf8');
    const out = new Set<string>();
    let m: RegExpExecArray | null;
    while ((m = HREF_RE.exec(html))) {
      const target = normalize(m[1], fromPath);
      if (!target) continue;
      if (target === fromPath) continue; // self-link, ignore
      out.add(target);
    }
    outbound.set(fromPath, out);
    for (const t of out) {
      if (!inbound.has(t)) inbound.set(t, new Set());
      inbound.get(t)!.add(fromPath);
    }
  }

  // Third pass — find broken internal links (target not in pages set).
  for (const [from, outs] of outbound) {
    for (const to of outs) {
      // Skip non-HTML resources (images, etc.) by extension.
      if (/\.(png|jpg|jpeg|webp|svg|ico|gif|pdf|xml|txt|json|css|js|woff2?|mp4|mp3|csv|gz|webmanifest|map|zip)$/i.test(to)) continue;
      // Template placeholders ({slug}, {competitor}) — only generated by
      // the playbook page rendering literal template strings. Not real
      // links; skip.
      if (to.includes('%7B') || to.includes('{')) continue;
      if (!pages.has(to)) broken.push({ from, to });
    }
  }

  return { pages, inbound, outbound, broken };
}

function main(): void {
  if (!fs.existsSync(DIST)) {
    console.error('No dist/ — run `pnpm build` first.');
    process.exit(1);
  }

  const { pages, inbound, broken } = audit();

  // Orphans: pages with zero inbound internal links. Exclude root /, /404,
  // and any page explicitly intended as not-from-nav (none right now).
  const ignored = new Set<string>(['/', '/404/', '/thanks/']);
  const orphans = [...pages].filter((p) => !ignored.has(p) && (inbound.get(p)?.size ?? 0) === 0).sort();

  // Hubs — top 10 by inbound link count.
  const hubs = [...inbound.entries()]
    .map(([p, links]) => [p, links.size] as const)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);

  console.log(`Total pages:        ${pages.size}`);
  console.log(`Orphan pages:       ${orphans.length}`);
  console.log(`Broken int. links:  ${broken.length}`);

  if (orphans.length) {
    console.log('\n— Orphan pages (no inbound internal links) —');
    for (const o of orphans.slice(0, 30)) console.log(`  ${o}`);
    if (orphans.length > 30) console.log(`  … +${orphans.length - 30} more`);
  }

  console.log('\n— Top 10 hub pages by inbound link count —');
  for (const [p, n] of hubs) console.log(`  ${String(n).padStart(4)} ← ${p}`);

  if (broken.length) {
    console.log('\n— Broken internal links —');
    const byTarget = new Map<string, Set<string>>();
    for (const b of broken) {
      if (!byTarget.has(b.to)) byTarget.set(b.to, new Set());
      byTarget.get(b.to)!.add(b.from);
    }
    for (const [to, froms] of byTarget) {
      console.log(`  ✗ ${to}`);
      for (const f of [...froms].slice(0, 3)) console.log(`      from ${f}`);
      if (froms.size > 3) console.log(`      … +${froms.size - 3} more`);
    }
    process.exit(1);
  }
}

main();
